[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "piecad"
description = '"Easy as Pie" CAD (Piecad)'
readme = "README.md"
authors = [{name = "Brian Sturgill", email = "codersnext@gmail.com"}]
license = {file = "LICENSE"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License"
]
dynamic = ["version"]
dependencies = [
    "piecad_viewer >= 1.0.4",
    "pillow >= 12.3.0",
    "trimesh[easy] >= 1.26.4",
    "fontPens >= 0.2.4",
    "fontTools >= 4.57.0",
    "manifold3d >= 3.0.1",
    "skia-pathops >= 0.8.0",
		"svgpathtools==1.7.0",
]

[project.urls]
Home = "https://github.com/briansturgill/Piecad"
Source = "https://github.com/briansturgill/Piecad"
Documentation = "https://briansturgill.github.io/Piecad/"
Examples = "https://github.com/briansturgill/Piecad/blob/main/examples/README.md"
"Bug Tracker" = "https://github.com/briansturgill/Piecad/issues"

[tool.flit.sdist]
include = ["html"]
exclude = [".benchmarks"]

[tool.pytest.ini_options]
pythonpath = [ "../piecad" ]
