#!/bin/sh
models="../html/piecad/models"
examples="../html/piecad/examples"
if [ ! -d $models ]; then
	mkdir $models
fi
if [ ! -d $examples ]; then
	mkdir $examples
fi
for f in *.example; do
	echo $f
	python process_example.py $f
done

mv tmp/*.glb $models
mv tmp/*.html $examples
rm tmp/*.py
